"use client"

import dynamic from "next/dynamic"
import { motion } from "framer-motion"
import { Copy, RefreshCw, Download, Share, AlertTriangle, Info } from "lucide-react"
import { AnimatedButton } from "@/components/ui/animated-button"
import { useTheme } from "@/lib/theme-context"
import Image from "next/image"
import { OutputContextMenu } from "./context-menu"
import { useState } from "react"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

// Dynamically import SyntaxHighlighter to avoid SSR issues
const SyntaxHighlighter = dynamic(() => import("react-syntax-highlighter").then((mod) => mod.Prism), { ssr: false })

const vscDarkPlus = dynamic(
  () => import("react-syntax-highlighter/dist/esm/styles/prism").then((mod) => mod.vscDarkPlus),
  { ssr: false },
)

// Define animation variants directly in the component to avoid issues
const messageAnimations = {
  initial: { opacity: 0, y: 10 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -10 },
  transition: { duration: 0.3 },
}

interface ChatMessageProps {
  content: string | null
  role: "user" | "assistant"
  mode?: string
  onCopy?: () => void
  onRegenerate?: () => void
  pinned?: boolean
  onPin?: () => void
  imageUrl?: string
  error?: boolean
  fallbackUsed?: boolean
}

export function ChatMessage({
  content,
  role,
  mode = "chat",
  onCopy,
  onRegenerate,
  pinned,
  onPin,
  imageUrl,
  error = false,
  fallbackUsed = false,
}: ChatMessageProps) {
  const { theme, isDarkMode } = useTheme()
  const isCode = mode === "code" && role === "assistant"
  const isImage = mode === "image" && role === "assistant" && imageUrl
  const [imageLoaded, setImageLoaded] = useState(false)
  const [imageLoadError, setImageLoadError] = useState(false)

  // Ensure content is always a string to prevent FatalRendererError
  const safeContent = content === null || content === undefined ? "" : String(content)

  const detectLanguage = (code: string | null): string => {
    // Ensure code is a string before using string methods
    if (typeof code !== "string" || !code) return "plaintext"

    // Simple language detection based on common patterns
    if (code.includes("import ") && code.includes("from ")) return "typescript"
    if (code.includes("def ") || code.includes("print(")) return "python"
    if (code.includes("function ") || code.includes("const ")) return "javascript"
    return "plaintext"
  }

  const handleDownload = () => {
    if (!imageUrl) return

    try {
      // For base64 images
      if (imageUrl.startsWith("data:")) {
        const link = document.createElement("a")
        link.href = imageUrl
        link.download = `mio-ai-image-${Date.now()}.jpg`
        document.body.appendChild(link)
        link.click()
        document.body.removeChild(link)
      } else {
        // For URL images
        fetch(imageUrl)
          .then((response) => response.blob())
          .then((blob) => {
            const url = window.URL.createObjectURL(blob)
            const link = document.createElement("a")
            link.href = url
            link.download = `mio-ai-image-${Date.now()}.jpg`
            document.body.appendChild(link)
            link.click()
            document.body.removeChild(link)
            window.URL.revokeObjectURL(url)
          })
      }
    } catch (error) {
      console.error("Error downloading image:", error)
    }
  }

  const handleShare = async () => {
    if (!imageUrl || !navigator.share) return

    try {
      let blob: Blob

      // For base64 images
      if (imageUrl.startsWith("data:")) {
        const base64Response = await fetch(imageUrl)
        blob = await base64Response.blob()
      } else {
        // For URL images
        const response = await fetch(imageUrl)
        blob = await response.blob()
      }

      const file = new File([blob], "mio-ai-image.jpg", { type: "image/jpeg" })

      await navigator.share({
        title: "Image generated by Mio AI",
        files: [file],
      })
    } catch (error) {
      console.error("Error sharing image:", error)
    }
  }

  const handleImageError = () => {
    setImageLoadError(true)
    setImageLoaded(true) // Stop the loading animation
    console.error("Failed to load image:", imageUrl)
  }

  return (
    <div className={`flex items-start gap-3 mb-6 ${role === "user" ? "flex-row-reverse" : ""}`}>
      {/* Avatar */}
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3 }}>
        <Avatar className={`${role === "assistant" ? "bg-primary-600" : "bg-secondary-700"} h-8 w-8`}>
          {role === "assistant" ? (
            <AvatarFallback>AI</AvatarFallback>
          ) : (
            <AvatarImage src="https://ui-avatars.com/api/?name=User&background=random" />
          )}
        </Avatar>
      </motion.div>

      {/* Message content */}
      <motion.div
        className={`max-w-[85%] ${role === "user" ? "items-end" : "items-start"}`}
        initial={{ opacity: 0, x: role === "user" ? 20 : -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.4 }}
      >
        <OutputContextMenu
          onCopy={onCopy}
          onRegenerate={role === "assistant" ? onRegenerate : undefined}
          onDownload={isImage ? handleDownload : undefined}
          onShare={isImage ? handleShare : undefined}
          isImage={isImage}
        >
          {isCode ? (
            <motion.div className="bg-secondary-900 rounded-lg overflow-hidden shadow-md" {...messageAnimations}>
              <div className="flex justify-between items-center px-4 py-2 bg-secondary-800">
                <span className="text-sm text-secondary-400">Code</span>
                <div className="flex gap-2">
                  <AnimatedButton variant="ghost" size="sm" animation="subtle" onClick={onCopy}>
                    <Copy className="h-4 w-4" />
                  </AnimatedButton>
                  {onRegenerate && (
                    <AnimatedButton variant="ghost" size="sm" animation="subtle" onClick={onRegenerate}>
                      <RefreshCw className="h-4 w-4" />
                    </AnimatedButton>
                  )}
                </div>
              </div>
              {SyntaxHighlighter && vscDarkPlus ? (
                <SyntaxHighlighter
                  language={detectLanguage(safeContent)}
                  style={vscDarkPlus}
                  customStyle={{
                    margin: 0,
                    padding: "1rem",
                    background: "transparent",
                  }}
                >
                  {safeContent}
                </SyntaxHighlighter>
              ) : (
                <pre className="p-4 overflow-x-auto text-sm font-mono">{safeContent}</pre>
              )}
            </motion.div>
          ) : (
            <motion.div
              className={`p-4 rounded-lg shadow-md ${error ? "border-l-4 border-warning-500" : ""}`}
              style={{
                backgroundColor:
                  role === "user"
                    ? isDarkMode
                      ? "rgba(59, 130, 246, 0.15)"
                      : "rgba(59, 130, 246, 0.1)"
                    : isDarkMode
                      ? "rgba(30, 41, 59, 0.7)"
                      : "rgba(241, 245, 249, 0.7)",
                backdropFilter: "blur(8px)",
                color: theme.foreground,
              }}
              {...messageAnimations}
            >
              {error ? (
                <div className="flex items-start gap-2">
                  <AlertTriangle className="h-5 w-5 text-warning-500 mt-0.5 flex-shrink-0" />
                  <div>
                    <p className="font-semibold text-warning-500 mb-1">Error</p>
                    <p>{safeContent}</p>
                  </div>
                </div>
              ) : (
                <div className="whitespace-pre-wrap break-words">{safeContent}</div>
              )}

              {isImage && imageUrl && (
                <motion.div
                  className="mt-4 relative"
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.5, delay: 0.2 }}
                >
                  <div
                    className={`rounded-lg overflow-hidden ${!imageLoaded ? "bg-secondary-800 animate-pulse" : ""}`}
                    style={{ minHeight: imageLoaded ? "auto" : "300px" }}
                  >
                    <Image
                      src={imageUrl || "/placeholder.svg"}
                      alt="Generated image"
                      width={512}
                      height={512}
                      className="rounded-lg w-full h-auto"
                      onLoad={() => setImageLoaded(true)}
                      onError={handleImageError}
                      unoptimized // Important for base64 images
                    />
                  </div>

                  {imageLoadError && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-secondary-800/80 rounded-lg">
                      <AlertTriangle className="h-10 w-10 text-warning-500 mb-2" />
                      <p className="text-center text-white text-sm">Image failed to load</p>
                      {onRegenerate && (
                        <Button
                          onClick={onRegenerate}
                          variant="outline"
                          size="sm"
                          className="mt-2 bg-black/30 text-white border-white/20"
                        >
                          <RefreshCw className="h-3 w-3 mr-1" />
                          Regenerate
                        </Button>
                      )}
                    </div>
                  )}

                  {fallbackUsed && !imageLoadError && (
                    <motion.div
                      className="absolute top-2 left-2 bg-warning-500/80 text-black text-xs px-2 py-1 rounded-md backdrop-blur-sm flex items-center"
                      initial={{ opacity: 0, y: -10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.3, delay: 0.5 }}
                    >
                      <Info className="h-3 w-3 mr-1" />
                      Fallback model used
                    </motion.div>
                  )}

                  {!imageLoadError && (
                    <motion.div
                      className="absolute bottom-2 right-2 flex gap-2"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ duration: 0.3, delay: 0.7 }}
                    >
                      <AnimatedButton
                        onClick={handleDownload}
                        size="sm"
                        animation="scale"
                        className="bg-black/50 hover:bg-black/70 backdrop-blur-sm"
                      >
                        <Download className="h-4 w-4 mr-1" />
                        Download
                      </AnimatedButton>
                      {navigator.share && (
                        <AnimatedButton
                          onClick={handleShare}
                          size="sm"
                          animation="scale"
                          className="bg-black/50 hover:bg-black/70 backdrop-blur-sm"
                        >
                          <Share className="h-4 w-4 mr-1" />
                          Share
                        </AnimatedButton>
                      )}
                    </motion.div>
                  )}
                </motion.div>
              )}
            </motion.div>
          )}
        </OutputContextMenu>
      </motion.div>
    </div>
  )
}
